### ISSUE TITLE
Division by 1

### ISSUE THREAD

**Issue by iddqd-dev** [a14n/dart-decimal#106]
Why when dividing 89.7869 by 1 the console displays 897869/10000 instead of 89.7869?

```
print(Decimal.parse('89.7869') / Decimal.one);

I/flutter ( 4826): 897869/10000
```

**Comment by a14n** [comment]
The division operator `/` returns a `Rational` because a division of 2 decimals is not always a decimal. If you want to convert it to Decimal, you can use the extensions provided by [RationalExt](https://pub.dev/documentation/decimal/latest/decimal/RationalExt.html) (especially [toDecimal()](https://pub.dev/documentation/decimal/latest/decimal/RationalExt/toDecimal.html)).

```dart
final rationalValue = Decimal.parse('89.7869') / Decimal.one;
final decimalValue = rationalValue.toDecimal();
```

**Comment by iddqd-dev** [comment]
Thanks for answer, it's work for me!
