### ISSUE TITLE
Enhancement: Round at a certain number of places after decimal.

### ISSUE THREAD

**Issue by davidfaulks** [a14n/dart-decimal#20]
It would be nice to have an efficient method that produces a Decimal rounded to a certain number of positions after the decimal (useful to keep performance up when calculating e^n and the like).

**Comment by a14n** [comment]
You should be able to do that today with something like:

```dart
// NOT TESTED
Decimal roundAt(Decimal value, int digit) {
  final m = Decimal.parse('1' + '0' * digit);
  return (value * m).round() / m;
}
```

**Comment by davidfaulks** [comment]
I have implemented that. I guess I am hoping for a way that avoids doing a multiplication and a division.

**Comment by a14n** [comment]
I'm not planning to add this feature because:
- I'd like to keep the API close to the `num` interface
- there are several rounding-related operations (`round()`, `floor()`, `ceil()`, `truncate()`...) and if we add this enhancement to `round()` I think other should have that. I'm not sure it is worth it.
