### ISSUE TITLE
double to decimal

### ISSUE THREAD

**Issue by kgrigorian** [a14n/dart-decimal#27]
would be useful to have double to decimal casting option.

**Comment by a14n** [comment]
Unfortunately there's no guarantee that a double can be represented as a decimal.

Even if we could do the trick [like Java BigDecimal does](https://docs.oracle.com/javase/7/docs/api/java/math/BigDecimal.html#BigDecimal(double)) my feeling is that it would lead to headaches and incomprehensions regarding simple cases like:

>One might assume that writing new BigDecimal(0.1) in Java creates a BigDecimal which is exactly equal to 0.1 (an unscaled value of 1, with a scale of 1), but it is actually equal to 0.1000000000000000055511151231257827021181583404541015625

```dart
var a = Decimal.fromDouble(0.1);
print(a); // 0.1000000000000000055511151231257827021181583404541015625
// WAT ???
```

That's why I prefer to avoid this kind of conversions.

**Comment by mwawrusch** [comment]
There is an easy workout around for that: Specify the significant fractional digits, e.g. Decimal.fromDouble(0.1, 1)
