### ISSUE TITLE
Support control of precision and parsing formats.

### ISSUE THREAD

**Issue by bsutton** [a14n/dart-decimal#51]
I'm the author of the dart Money2 package and we are looking for a class to hold Fixed Precision decimal values and came across your package which we would like to use.

We have identified a number of gaps in the requirements that would stop us using the decimal package in its current form.

We are interested in seeing the decimal api extended to support the following constructors:

```dart
Decimal.parse(String amount, { String pattern = '#.#',  int precision, bool invertSeparators});
Decimal.from(num amount, int precision);
Decimal.fromInt(int amount, int precision);
Decimal.fromBigInt(BigInt amount, int precision);
```

## Parse method
The pattern for the parser allows us to support various formats for the amount string including thousand separators.
The invertSeparators flag indicates to the parser that the decimal and thousands separators are inverted (as used by european countries vs the usa).

The precision overrides the precision passed in the amount string.  An example is where a users passes '0.01' with a precision of three. With your current implementation the Decimal would have a precision of 2, with the proposed changed the precision would be 3.

## from(num amount, int precision)
The num can be a double which we force to precision decimal places.

## fromInt(int amount, int precision)
The amount is in 'minor units' as described by the precision. e.g to represent 1.00 with a precision of 2 you would pass 100 as the amount and 2 as the precision:

```dart
Decimal.fromInt(100, 2) == 1.00;
```

The same approach applies to fromBigInt.

I believe the above changes would be backward compatible with the the current Decimal api.

I think the main point of contention is the pattern. We have taken a roll your own approach rather than relying on locales in the belief that it provides the end user with the most flexibility.

Would the above be functionality you would consider adding to the Decimal class?

Would you accept a PR with the above changes?

**Comment by a14n** [comment]
Thanks for your interest and your suggestions.

This `decimal` package tries to have a general purpose on decimal computations. Currency/money handling is one use-case among others.

My first feeling is that those new constructors could be functions out of the decimal package. What would be the value for you if it became part of the Decimal class?

Here's my comments for each proposal:

## Decimal.parse

>```dart
>Decimal.parse(String amount, { String pattern = '#.#',  int precision, bool invertSeparators});
>```

Numeric/conrrency/money formats rely on internationalization and localization. I think this shouldn't be handled directly in the `decimal` package but rather by `intl` or something out of `decimal.dart` (basically a [NumberFormat](https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html) that handles `BigInt` instead of `int`)

I'm also concerned about the absence of locale because when I see pattern of number formatting I always think that the point in `#.#` means decimal separator as stated in [NumberFormat](https://pub.dev/documentation/intl/latest/intl/NumberFormat-class.html) and I expect an associated locale. So I don't think the signature would be well understood.

## Decimal.from

This could be implemented (modulo some rounding issues) as:

```dart
  Decimal from(num amount, int precision) =>
      Decimal.parse(amount.toStringAsFixed(precision)); // precision must be between 0 and 20
```

But I always be reticent to accept `double` (See #27). Even with a `precision` param this could lead to issues. For instance `(1/3).toStringAsFixed(20)` is `0.33333333333333331483`.

## Decimal.fromInt

This can be implemented as:

```dart
  final ten = Decimal.fromInt(10);
  Decimal fromInt(int amount, int precision) =>
      Decimal.fromInt(amount) / ten.pow(precision);
```

`precision` is not a good name here imho because it's not exactly the same thing as the `precision` used in `Decimal.from`.


## Decimal.fromBigInt

If I add a `Decimal.fromBigInt` (that is likely to happen) this could be implemented as:

```dart
  final ten = Decimal.fromInt(10);
  Decimal fromBigInt(BigInt amount, int precision) =>
      Decimal.fromBigInt(amount) / ten.pow(precision);
```
