### ISSUE TITLE
No `parse` getter in Decimal

### ISSUE THREAD

**Issue by HualiangLI** [a14n/dart-decimal#53]
Used as it decribed in the readme as bellow:
```dart
import 'package:decimal/decimal.dart';
final d = Decimal.parse;
```

It shows an error prompt in VSC for `the getter 'parse' isn't defined for the type 'Decimal'.`

**Comment by a14n** [comment]
Good catch!

At the time of writting the code you quote from the README `parse` was a static method and the example was ok. Later I changed it to a factory constructor to conform to the rule `prefer_constructors_over_static_methods`. This was not compatible with this code snippet (because Dart didn't support constructor tear-off) and I should have change it to `final d = (String s) => Decimal.parse(s);`. a future version of Dart should support constructor tear-off, this snippet should then be valid. 

(if I could come back in past I'd probably not make this change again - static method to factory - for [some reasons](https://github.com/dart-lang/linter/issues/2909#issuecomment-909063186) and because the rule `prefer_constructors_over_static_methods` is no longer in the style guide)
