### ISSUE TITLE
Make zero and one const

### ISSUE THREAD

**Issue by treeder** [a14n/dart-decimal#54]
Would it make sense to make `static Decimal.zero` and `static Decimal.one` const's?  Then they could be used for setting default values in constructors.

**Comment by andoutica** [comment]
I got the same issue, cannot set default values in contructors

**Comment by a14n** [comment]
Because `Decimal` implementation relies on [BigInt](https://api.dart.dev/stable/2.13.4/dart-core/BigInt-class.html) (that don't have const constructors) no Decimal can be const.

> cannot set default values in constructors

There has been discussion on the language team to relax this constraint and allow default value that are not const... but this has not yet happen.
