### ISSUE TITLE
The `/` operator between two `Decimal` should return a `Decimal`

### ISSUE THREAD

**Issue by cedric-booxi** [a14n/dart-decimal#67]
It seems like a strange choice to have the `/` operator between two `Decimal` return a `Rational`, especially when other operators return a `Decimal`. 

Is there a specific reason for that behavior ?

If not I'm offering to open a small PR to change that.

**Comment by a14n** [comment]
It was an intentional choice done in [version 2](https://github.com/a14n/dart-decimal/blob/master/CHANGELOG.md#200-2021-11-29) to avoid having `Decimal` that is not a decimal (a number that can be written with a finite number of digits). For instance though 1 and 3 are decimal numbers 1/3 is not a decimal.

> `inverse`, `/` now return a `Rational`. If you need a `Decimal` you can convert the `Rational` to `Decimal` with `rational.toDecimal(scaleOnInfinitePrecision: xxx)`. If you need to make several computations where inverses or divisions are involved you should make thoses operations on `Rational` type to avoid loosing precision and at the end convert the result back to `Decimal` if you want to display the result in a decimal form.

Before version 2  `dec(1)/dec(3)` was returning a `Decimal` that had not a finite precision and this had lead to several issues.


> especially when other operators return a `Decimal`.

With 2 decimal `a` and `b`, `a+b`, `a-b`, `a*b` are always decimals but `a/b` is not always a decimal.

If you need to get a `Decimal` out from division take a look at `rational.toDecimal(scaleOnInfinitePrecision: xxx)` or `rational.toDecimal()` to get a Decimal.
