### ISSUE TITLE
Add method to convert double to Decimal/Rational

### ISSUE THREAD

**Issue by dalewking** [a14n/dart-decimal#75]
I realize this is a dupe of #27 and this request applies to both Decimal and Rational libraries, but there needs to be a way to convert from a double. The difference here is that I am giving you the code that does the conversion. Here is an extension I wrote to workaround this missing feature:

```
extension RationalExtOnDouble on double {
  Rational get asRational {
    // Don't allow NaN, or infinite
    assert(isFinite);
    ByteData d = ByteData(8);
    d.setFloat64(0, this);
    final u = d.getUint32(0);
    final l = d.getUint32(4);
    int exponent = (u >> 20) & 0x7FF;
    final fraction = ((u & 0xFFFFF) << 32) + l;
    int significand = exponent == 0
        // 0 exponent means either a signed zero or subnormal
        ? fraction << 1
        // non-zero is normal case where significand is 1.fraction
        : fraction | (1 << 52);
    
    if (significand == 0)
      return Rational.zero;
    else {
      exponent -= 1075;

      while (significand & 1 == 0) {
        significand >>= 1;
        exponent++;
      }

      final a = BigInt.from((u & 0x80000000) == 0 ? significand : -significand);
      final BigInt b = exponent == 0 ? BigInt.one : BigInt.two.pow(exponent.abs());

      return exponent <= 0 ? Rational(a, b) : Rational(a * b);
    }
  }
}
```

In #27 you said that this could be confusing because someone might expect `Decimal.fromDouble(0.1)` to actually be 0.1, but that is more about their misunderstanding of how double works than a failing of the conversion. I can tell you that this is generally not an issue because this is how BigDecimal in Java has operated for nearly 20 years.

**Comment by a14n** [comment]
The extension you wrote is almost the same I used when [I commented #27](https://github.com/a14n/dart-decimal/issues/27#issuecomment-532110116). 

`0.1.asRational.toDecimal()` is the same as `Decimal.parse('0.1000000000000000055511151231257827021181583404541015625')`. This is misleading and error prone.

People are using `Decimal` to avoid losing precision and this example above is exactly what they want to avoid. That's why I really want people to be really careful converting double to Decimal.

If an extension would allow something like `0.1.toDecimal()` I'm sure that new issues will be filed every day/week to complain that `0.1` is convert to `0.1000000000000000055511151231257827021181583404541015625`. Forcing users to use `Decimal.parse('0.1')` instead of `0.1.toDecimal()` avoids bugs.

If someone want to convert a double to Decimal I'd recommend to convert it to String (with `toStringAsFixed` for example) and then to Decimal.

> but that is more about their misunderstanding of how double works

I agree and I think a lot of people doesn't understand how double are handled under the cover. Preventing them to do mistakes is a big win :)

> I can tell you that this is generally not an issue because this is how BigDecimal in Java has operated for nearly 20 years.

Java policy tends to avoid breaking changes so a 20 years old feature doesn't mean it is a good API ;)
