### ISSUE TITLE
Handle divisions the same way it handles other operations.

### ISSUE THREAD

**Issue by Wenutz** [a14n/dart-decimal#76]
Why is it that division return a rational number as opposed to a result?
 
I am trying to do

```
Decimal d= Decimal.parse(1) / Decimal.parse(2)  
//It returns the rational 1/2 instead of  the expected double 0.5.
```

Other operands (+,-,*) actually triggers a calculation. Would be good if it was the same for division otherwise it is inconsistent.

**Comment by a14n** [comment]
A `Decimal` represents a number that can be displayed with a finite number of digit. `Decimal.parse(1) / Decimal.parse(2)` is definitely a decimal (0.5) but other division results (like `Decimal.parse(1) / Decimal.parse(3)`) are not decimals. In those cases the result is a rational number (that can be represented by a fraction between 2 integers). Returning a Decimal in that case would mean a precision lost (0.3333333 instead of 0.3333333333333333...). That's why division (and some other operations) returns a Rational.

You can read more in https://github.com/a14n/dart-decimal/blob/master/CHANGELOG.md#201-2021-12-20
