### ISSUE TITLE
`toInt()` method

### ISSUE THREAD

**Issue by ferraridamiano** [a14n/dart-decimal#77]
Hi and thank you for this package. I'm interested in a `toInt()` method on the `Decimal class`. The only way of achieving this at the moment is by performing `.toBigInt().toInt()`.

Does this make sense to you? If yes I could try submitting a PR to fix this issue

**Comment by a14n** [comment]
Thanks for your feedback and the proposition.

Before the 2.0.0 version there was a `toInt()` method. I removed it to prevent mistakes because you can get a completly wrong results (`BigInt.parse('1${'0' * 20}').toInt()` prints `100000000000000000000` on the web and `9223372036854775807` on VM). I think that someone using decimal cares about precision and this method would completly defeats this goal. So I prefer to make it harder to convert Decimal to int. Moreover I don't think this kind of convertion is used frequently.
