### ISSUE TITLE
 Eror

### ISSUE THREAD

**Issue by rhymelph** [a14n/dart-decimal#78]
<img width="894" alt="image" src="https://user-images.githubusercontent.com/20870368/180746735-fb893a71-0f8a-40bb-b936-37cb4db71a8e.png">

**Comment by rhymelph** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/20870368/180747756-d4315099-e57f-4bd5-b768-e9bd091f538d.png">

**Comment by a14n** [comment]
See https://pub.dev/documentation/decimal/latest/decimal/RationalExt/toDecimal.html

Basically you try to convert a `Rational` that has not a finite decimal precision (like `1/3`) into a `Decimal`. The API throws in that case because there will be a precision lost. The API requires that you explicitally provide the precision you accept to lose : `rational.toDecimal(scaleOnInfinitePrecision: 10)`

**Comment by rhymelph** [comment]
version 0.3.5  not this issues. when i upgrade new version , this error throw out.
