### ISSUE TITLE
2.3.0 breaking change 

### ISSUE THREAD

**Issue by ruicraveiro** [a14n/dart-decimal#89]
Hi,

Version 2.3.0 is a breaking change. Can you please republish it as 3.0.0?

Thanks!

Rui

**Comment by a14n** [comment]
Sorry about that.

I hesitated between 3.0.0 and 2.3.0 when I changed the `pow` return type. I went with 2.3.0 for 2 reasons:

* It was bug in the API to return a `Decimal` as `dec('3').pow(-1)` was throwing an exception. So yes, it's a breaking change regarding the code but not really regarding the design of the API in 2.x (an operation that can lead to a rational without a finite decimal representation must return a `Rational` to prevent silent precision lost)
* I expected that `pow` was not widely used and it should take too long to fix its usages

Now that 2.3.0 is published publishing a 3.0.0 wouldn't fix anything. That's why I will close this issue as _Not Planed_.
