### ISSUE TITLE
why can't divide two decimals it says rational can't be assigned to decimal? why

### ISSUE THREAD

**Issue by wajahat414** [a14n/dart-decimal#94]

**Comment by a14n** [comment]
A `Decimal` represents a number that can be displayed with a finite number of digit. `Decimal.parse(1) / Decimal.parse(2)` is definitely a decimal (0.5) but other division results (like `Decimal.parse(1) / Decimal.parse(3)`) are not decimals. In those cases the result is a rational number (that can be represented by a fraction between 2 integers). Returning a Decimal in that case would mean a precision lost (0.3333333 instead of 0.3333333333333333...). That's why division (and some other operations) returns a Rational.

You can read more in https://github.com/a14n/dart-decimal/blob/master/CHANGELOG.md#200-2021-11-29
